### PR TITLE
Separate go module for buoy

### PR DESCRIPTION
**Pull request by dims**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Please see https://github.com/kubernetes/kubernetes/issues/99562, we need to avoid kubernetes/kubernetes depending on itself. 

So split out `buoy` which is a standalone utility to have its own go.mod/go.sum

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by BenTheElder — COMMENTED** [review]
probably should update `hack/verify-go-mod.sh` to cover this? (cd `buoy && go mod tidy`)
the linter script likely also needs an update, not sure what else from a quick skim, maybe the releaser config.
EDIT: and thanks dims!

**Comment by BenTheElder** [comment]
I don't think this drops k8s.io/kubernetes from the root go.mod, but it does drop k8s.io/apimachinery which is probably still desirable. the root go.sum line 1503 still references k8s.io/kubernetes.

**Comment by dims** [comment]
`"k8s.io/release"` -> `"cloud.google.com/go/storage"` -> `"github.com/Microsoft/\nhcsshim"` -> `"k8s.io/kubernetes"`

**Pull request closed without merging**
