### PR TITLE
validate: fix base path when validating locally

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

not assume that the config directory is the same as the search directory

some running examples in k/k

```console
$ zeitgeist validate --local --config /Users/cpanatojr/code/src/k8s.io/kubernetes/build/dependencies.yaml --log-level debug
DEBU Setting commands globally into verbose mode
DEBU Using log level "debug"                       file="cmd/root.go:68"
INFO Validating zeitgeist options...               file="cmd/validate.go:111"
DEBU Base path /Users/cpanatojr/code/src/k8s.io/kubernetes  file="dependencies/dependencies.go:136"
DEBU Deserialised Dependency agnhost: &{agnhost 2.27 semver  map[] [0xc000716e20 0xc000716e40]}  file="dependencies/dependencies.go:111"
DEBU Deserialised Dependency agnhost: dependents: &{agnhost: dependents 2.26 semver  map[] [0xc000717000]}  file="dependencies/dependencies.go:111"
DEBU Deserialised Dependency repo-infra: &{repo-infra 0.2.0 semver  map[] [0xc000717140 0xc000717160]}  file="dependencies/dependencies.go:111"
....
DEBU Examining dependency: agnhost                 file="dependencies/dependencies.go:144"
DEBU Examining file: /Users/cpanatojr/code/src/k8s.io/kubernetes/test/images/agnhost/VERSION  file="dependencies/dependencies.go:155"
DEBU Line 1 matches expected regexp '\d.\d' and version '2.27': 2.27  file="dependencies/dependencies.go:170"
DEBU Examining file: /Users/cpanatojr/code/src/k8s.io/kubernetes/test/images/agnhost/agnhost.go  file="dependencies/dependencies.go:155"
DEBU Line 54 matches expected regexp 'Version:' and version '2.27':             Version: "2.27",  file="dependencies/dependencies.go:170"
DEBU Examining dependency: agnhost: dependents     file="dependencies/dependencies.go:144"
DEBU Examining file: /Users/cpanatojr/code/src/k8s.io/kubernetes/test/utils/image/manifest.go  file="dependencies/dependencies.go:155"
DEBU Line 221 matches expected regexp 'configs\[Agnhost\] = Config{promoterE2eRegistry, "agnhost", "\d+\.\d+"}' and version '2.26':     configs[Agnhost] = Config{promoterE2eRegistry, "agnhost", "2.26"}  file="dependencies/dependencies.go:170"
DEBU Examining dependency: repo-infra              file="dependencies/dependencies.go:144"
DEBU Examining file: /Users/cpanatojr/code/src/k8s.io/kubernetes/build/root/WORKSPACE  file="dependencies/dependencies.go:155"
DEBU Line 9 matches expected regexp 'strip_prefix = "repo-infra-\d+.\d+.\d+"' and version '0.2.0':     strip_prefix = "repo-infra-0.2.0",  file="dependencies/dependencies.go:170"
DEBU Examining file: /Users/cpanatojr/code/src/k8s.io/kubernetes/build/root/WORKSPACE  file="dependencies/dependencies.go:155"
DEBU Line 11 matches expected regexp 'https://github.com/kubernetes/repo-infra/archive/v\d+.\d+.\d+.tar.gz' and version '0.2.0':         "https://github.com/kubernetes/repo-infra/archive/v0.2.0.tar.gz",  file="dependencies/dependencies.go:170"
DEBU Examining dependency: cni                     file="dependencies/dependencies.go:144"
DEBU Examining file: /Users/cpanatojr/code/src/k8s.io/kubernetes/build/workspace.bzl  file="dependencies/dependencies.go:155"
....
```

another base-path
```console
$ zeitgeist validate --local --config /Users/cpanatojr/code/src/k8s.io/kubernetes/build/dependencies.yaml --log-level debug --base-path /tmp
DEBU Setting commands globally into verbose mode
DEBU Using log level "debug"                       file="cmd/root.go:68"
INFO Validating zeitgeist options...               file="cmd/validate.go:111"
DEBU Base path /tmp                                file="dependencies/dependencies.go:136"
DEBU Deserialised Dependency agnhost: &{agnhost 2.27 semver  map[] [0xc00089c460 0xc00089c480]}  file="dependencies/dependencies.go:111"
DEBU Deserialised Dependency agnhost: dependents: &{agnhost: dependents 2.26 semver  map[] [0xc00089c5c0]}  file="dependencies/dependencies.go:111"
DEBU Deserialised Dependency repo-infra: &{repo-infra 0.2.0 semver  map[] [0xc00089c6e0 0xc00089c700]}  file="dependencies/dependencies.go:111"
DEBU Deserialised Dependency cni: &{cni 0.8.7 semver  map[] [0xc00089c820 0xc00089c840 0xc00089c860 0xc00089c880]}  file="dependencies/dependencies.go:111"
DEBU Deserialised Dependency coredns-kube-up: &{coredns-kube-up 1.7.0 semver  map[] [0xc00089c980 0xc00089c9a0 0xc00089c9c0]}  file="dependencies/dependencies.go:111"
DEBU Deserialised Dependency coredns-kubeadm: &{coredns-kubeadm 1.8.0 semver  map[] [0xc00089caa0]}  file="dependencies/dependencies.go:111"
DEBU Deserialised Dependency crictl: &{crictl 1.20.0 semver  map[] [0xc00089cbc0 0xc00089cbe0 0xc00089cc20]}  file="dependencies/dependencies.go:111"
DEBU Deserialised Dependency docker: &{docker 19.03 semver  map[] [0xc00089cd60]}  file="dependencies/dependencies.go:111"
DEBU Deserialised Dependency etcd: &{etcd 3.4.13 semver  map[] [0xc00089cee0 0xc00089cf00 0xc00089cf40 0xc00089cf60 0xc00089cfa0 0xc00089cfc0 0xc00089d000]}  file="dependencies/dependencies.go:111"
DEBU Deserialised Dependency etcd-image: &{etcd-image 3.4.13 semver  map[] [0xc00089d140 0xc00089d160]}  file="dependencies/dependencies.go:111"
DEBU Deserialised Dependency golang: upstream version: &{golang: upstream version 1.15.8 semver  map[] [0xc00089d240 0xc00089d260 0xc00089d280 0xc00089d2a0 0xc00089d2c0]}  file="dependencies/dependencies.go:111"
DEBU Deserialised Dependency k8s.gcr.io/kube-cross: dependents: &{k8s.gcr.io/kube-cross: dependents v1.15.8-1 semver  map[] [0xc00089d3a0 0xc00089d3c0]}  file="dependencies/dependencies.go:111"
DEBU Deserialised Dependency k8s.gcr.io/debian-base: dependents: &{k8s.gcr.io/debian-base: dependents buster-v1.4.0 semver  map[] [0xc00089d4a0 0xc00089d4c0 0xc00089d4e0 0xc00089d500 0xc00089d520 0xc00089d540]}  file="dependencies/dependencies.go:111"
DEBU Deserialised Dependency k8s.gcr.io/debian-iptables: dependents: &{k8s.gcr.io/debian-iptables: dependents buster-v1.5.0 semver  map[] [0xc00089d640 0xc00089d660 0xc00089d680]}  file="dependencies/dependencies.go:111"
DEBU Deserialised Dependency k8s.gcr.io/go-runner: dependents: &{k8s.gcr.io/go-runner: dependents buster-v2.3.1 semver  map[] [0xc00089d760 0xc00089d780]}  file="dependencies/dependencies.go:111"
DEBU Deserialised Dependency k8s.gcr.io/pause: &{k8s.gcr.io/pause 3.4 semver  map[] [0xc00089d860]}  file="dependencies/dependencies.go:111"
DEBU Deserialised Dependency k8s.gcr.io/pause: dependents: &{k8s.gcr.io/pause: dependents 3.2 semver  map[] [0xc00089d940 0xc00089d960 0xc00089d980 0xc00089d9a0 0xc00089d9c0 0xc00089d9e0 0xc00089da00 0xc00089da20 0xc00089da40 0xc00089da60 0xc00089da80 0xc00089daa0 0xc00089dac0 0xc00089dae0 0xc00089db00 0xc00089db20 0xc00089db40 0xc00089db60 0xc00089db80 0xc00089dba0 0xc00089dbc0 0xc00089dbe0 0xc00089dc00 0xc00089dc20]}  file="dependencies/dependencies.go:111"
DEBU Deserialised Dependency metadata-concealment: &{metadata-concealment 1.6 semver  map[] [0xc00089dd00]}  file="dependencies/dependencies.go:111"
DEBU Deserialised Dependency metadata-concealment: dependents: &{metadata-concealment: dependents 1.6 semver  map[] [0xc00089dde0]}  file="dependencies/dependencies.go:111"
DEBU Examining dependency: agnhost                 file="dependencies/dependencies.go:144"
ERRO Error opening /tmp/test/images/agnhost/VERSION: open /tmp/test/images/agnhost/VERSION: no such file or directory  file="dependencies/dependencies.go:151"
```

invalid path

```console
$ zeitgeist validate --local --config /Users/cpanatojr/code/src/k8s.io/kubernetes/build/dependencies.yaml --log-level debug --base-path /honk
DEBU Setting commands globally into verbose mode
DEBU Using log level "debug"                       file="cmd/root.go:68"
INFO Validating zeitgeist options...               file="cmd/validate.go:111"
FATA validating zeitgeist options: stat /honk: no such file or directory  file="cmd/root.go:54"
```

/assign @justaugustus 

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes-sigs/zeitgeist/issues/25

#### Does this PR introduce a user-facing change?

```release-note
validate: fix base path when validating locally
```

### CODE REVIEW

**Review by Pluies — APPROVED** [review]
Good call, that's great for flexibility! 👍

**Comment by cpanato** [comment]
@Pluies can I have another lgtm? updated the go.sum because the CI complained :)

**Comment by Pluies** [comment]
Sure thing! :)
/lgtm

**Pull request merged**
