### PR TITLE
Switch to `github.com/blang/semver/v4`

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Switching to the latest go module compatible version.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@kubernetes-sigs/release-engineering PTAL

**Review by xmudrii — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
@xmudrii I had to rebase this one :)

**Review by xmudrii — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
Thank you @xmudrii!

**Pull request merged**
