### PR TITLE
Helm support

### PR DESCRIPTION
**Pull request by Pluies**
#### What type of PR is this?

/kind documentation
/kind feature
/kind failing-test

#### What this PR does / why we need it:

Add support for Helm as an upstream! 🎉

Also big README updates, and fixes a tiny bug on the gitlab provider
where repositories containing a slash were broken.

#### Which issue(s) this PR fixes:

NONE

#### Special notes for your reviewer:

n/a

#### Does this PR introduce a user-facing change?

Yes, new functionality. All backwards-compatible.

### CODE REVIEW

**Comment by Pluies** [comment]
Hmm, the builds are still triggered in CircleCI despite us moving away from it... And stopping the builds now require admin permissions, which I don't have :( 

@justaugustus , when you have time (not urgent :) ) could you stop zeitgeist from building on CircleCI please? https://app.circleci.com/settings/project/github/kubernetes-sigs/zeitgeist?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fkubernetes-sigs%2Fzeitgeist

**Comment by Pluies** [comment]
(Note: leaving this one as a "In Progress" for now as I still need to fix the error handling and add tests!)

**Comment by cpanato** [comment]
you should not use the upstream repo to push branches, it is better to use your fork for that.

**Comment by cpanato** [comment]
about circleci this is weird past PRs did not trigger that

**Pull request closed without merging**
