### PR TITLE
Remove import cycles for downstream consumers

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

- internal: Copy in k/release@5b0e777
- Switch to zeitgeist `internal/` imports and `go mod tidy`
- buoy: Init module
- hack: Support multiple modules in verify-go-mod.sh
- upstreams: Drop helm support to remove k8s.io imports 

ref: https://github.com/kubernetes/kubernetes/pull/98845#discussion_r584370625, https://github.com/kubernetes/kubernetes/pull/99679

#### Does this PR introduce a user-facing change?

```release-note
- internal: Copy in k/release@5b0e777
- Switch to zeitgeist `internal/` imports and `go mod tidy`
- buoy: Init module
- hack: Support multiple modules in verify-go-mod.sh
- upstreams: Drop helm support to remove k8s.io imports 
```

### CODE REVIEW

**Comment by cpanato** [comment]
should we move the GitLab to the internal folder as well in a followup to match the changes in this PR?

**Comment by cpanato** [comment]
LGTM

**Comment by justaugustus** [comment]
FYI @dims @liggitt @BenTheElder.

/assign @cpanato @saschagrunert 
cc: @kubernetes-sigs/release-engineering @Pluies 
/priority critical-urgent

**Review by cpanato — APPROVED** [review]
/lgtm

i will check in how to add back the helm support

**Pull request merged**
