### PR TITLE
Use bookworm as ko release image

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Using the latest bookworm image for ko releases.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by cpanato** [comment]
i still prefer to have the latest then we dont need to update every time, just when we bump

**Comment by saschagrunert** [comment]
> i still prefer to have the latest then we dont need to update every time, just when we bump

The question is why do we promote the images then?

**Comment by saschagrunert** [comment]
Changed the PRs to just update the distribution rather than the whole registry.

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by cpanato** [comment]
403 API rate limit exceeded

😭

**Comment by cpanato** [comment]
> > i still prefer to have the latest then we dont need to update every time, just when we bump
> 
> The question is why do we promote the images then?

good question :D 
maybe we dont need that, but we need to do a search to see where the promoted image is used, otherwise we can stop the promotion

**Pull request merged**
