### PR TITLE
update to go1.19

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
- update to go1.19

/hold for job update

/assign @saschagrunert @Verolop @palnabarun @xmudrii 
cc @kubernetes-sigs/release-engineering 

#### Does this PR introduce a user-facing change?

```release-note
update to go1.19
```

### CODE REVIEW

**Comment by cpanato** [comment]
all green now @saschagrunert PTAL

**Review by Pluies — APPROVED** [review]

**Pull request merged**
